apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-production
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra-production
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.12.2
    helm:
      releaseName: metrics-server
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
